title: "Achute's Log"
description: "Random Dev/Sec thoughts & Write ups from various HTB/CTF/VulnHub"
baseurl: "/"
url: "https://achute.github.io"
header_pages:
  - index.md
  - hacklog.md
  - about.md

bye_message: '> follow me on <a href="https://twitter.com/achute">twitter</a> <'

# Header settings
nick: "Achutes Log"
mail:
    domain: "protonmail"
    ext: "com"
source_code:
    server: "github.com"
    nick: "achute"
# fingerprint_key: "xx"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
