title: 'HackLog'
description: "Write ups from various HTB / CTF / VulnHub"
baseurl: "/hacklog/"
url: "https://achute.github.io"
header_pages:
  - index.md
  - about.md

bye_message: '> follow us on <a href="https://twitter.com/achute">twitter</a> <'

# Header settings
nick: "achute"
mail:
    domain: "protonmail"
    ext: "com"
source_code:
    server: "github.com"
    nick: "achute"
# fingerprint_key: "xx"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
